src/Controller/MainController.php
<?php
namespace TrustOcean\Encryption365\Controller;

//_post()会返回所有POST参数，要获取POST参数中的username参数，请使用 _post('username')
//可通过_version()函数获取面板版本
//可通过_post('client_ip') 来获取访客IP

//常量说明：
//PLU_PATH 插件所在目录
//PLU_NAME 插件名称
//PLU_FUN  当前被访问的方法名称
use TrustOcean\Encryption365\Common\CertificateUtils;
use TrustOcean\Encryption365\Common\DatabaseUtils;
use TrustOcean\Encryption365\Common\Encryption365Service;
use TrustOcean\Encryption365\Common\NginxVhostUtils;
use TrustOcean\Encryption365\Common\TwigUtils;
use TrustOcean\Encryption365\Encryption365Exception;
use TrustOcean\Encryption365\Encryption365PageException;
use TrustOcean\Encryption365\Common\LogUtils;
use TrustOcean\Encryption365\Repository\SiteRep;

/**
 * Class MainController
 * @package TrustOcean\Encryption365\Controller
 */
class MainController{
    /**
     * @var \Twig\Environment
     */
    protected $twig;

    /**
     * MainController constructor.
     */
    public function __construct()
    {
        try{
            // 启动Twig引擎
            $this->twig = TwigUtils::initTwig();
            // 检查和初始化数据库
            $this->checkAndInstallDatabase();
            // 检查并设置自动化任务
             DatabaseUtils::installCronJob();
        }catch(\Exception $exception){
           die($exception->getMessage());
        }
    }

    /**
     * 检查是否已经设置了本地账户
     * @throws \Twig\Error\LoaderError
     * @throws \Twig\Error\RuntimeError
     * @throws \Twig\Error\SyntaxError
     */
    private function checkInitAcc() {
        // 检查是否已经进行了初始化账户绑定
        $db = DatabaseUtils::initLocalDatabase();
        $checkAcc = $clientInfo = $db->query("select * from configuration where `setting` in ('client_id','access_token')")->fetchAll();
        if(empty($checkAcc)){
            die(json_encode($this->twig->render('getAccountWelcome.html.twig')));
        }
    }

    /**
     * 注册新的账户页面
     * @return string
     * @throws \Twig\Error\LoaderError
     * @throws \Twig\Error\RuntimeError
     * @throws \Twig\Error\SyntaxError
     */
    public function getRegister() {
        return $this->twig->render('registerAccount.html.twig');
    }

    /**
     * 注册补充账户资料
     * @return string
     * @throws \Twig\Error\LoaderError
     * @throws \Twig\Error\RuntimeError
     * @throws \Twig\Error\SyntaxError
     */
    public function getRegisterTwo() {
        return $this->twig->render('registerAccountTwo.html.twig',['email'=>_post('email')]);
    }

    /**
     * @return string
     * @throws \Twig\Error\LoaderError
     * @throws \Twig\Error\RuntimeError
     * @throws \Twig\Error\SyntaxError
     */
    public function getSupport() {
        $this->checkInitAcc();
        return $this->twig->render('getSupport.html.twig');
    }

    /**
     * @return string
     * @throws \Twig\Error\LoaderError
     * @throws \Twig\Error\RuntimeError
     * @throws \Twig\Error\SyntaxError
     */
    public function getOnlineSupport() {
        $this->checkInitAcc();
        return $this->twig->render('onlineSupport.html.twig');
    }

    /**
     * @return string
     * @throws \Twig\Error\LoaderError
     * @throws \Twig\Error\RuntimeError
     * @throws \Twig\Error\SyntaxError
     */
    public function siteList(){
        $this->checkInitAcc();
        return $this->twig->render('siteList.html.twig');
    }

    /**
     * @return string
     * @throws \Twig\Error\LoaderError
     * @throws \Twig\Error\RuntimeError
     * @throws \Twig\Error\SyntaxError
     */
    public function getOrgTempList() {
        $this->checkInitAcc();
        return $this->twig->render('organizationTemplate.html.twig');
    }

    /**
     * 保存新的组织信息
     * @return array
     */
    public function createNewOrganization() {
        try{
            $db = DatabaseUtils::initLocalDatabase();
            $keys = [
                'organization_name',
                'organizationalUnitName',
                'registered_address_line1',
                'registered_no',
                'country',
                'state',
                'city',
                'postal_code',
                'organization_phone',
                'date_of_incorporation',
                'contact_name',
                'contact_title',
                'contact_phone',
                'contact_email'
            ];
            $newOrg = [];
            foreach ($keys as $name){
                $newOrg[$name] = _post($name);
            }

            $db->query('insert into organization_template ?', $newOrg);
            LogUtils::writeLog(LogUtils::STATUS_SUCCESS,LogUtils::TITLE_ORG_CREATE,'新的组织模板创建成功, 组织:'._post('organization_name'));
            return ['status'=>"success"];
        }    catch (\Exception $e){
            LogUtils::writeLog(LogUtils::STATUS_ERROR,LogUtils::TITLE_ORG_CREATE,'新的组织模板创建失败, 组织:'._post('organization_name'));
            return ['status'=>"error","message"=>'保存出错，该组织名称已存在或信息格式错误'];
        }
    }

    /**
     * 移除证书订单
     * @return array
     */
    public function removeSSLOrder()
    {
        try{
            $site = SiteRep::getSiteInfo(_post('siteName'));
            $db = DatabaseUtils::initLocalDatabase();
            $db->query('delete from certificate where site_id = ?', $site['id']);
            return ['status'=>"success","message"=>"订单删除成功"];
        }catch (\Exception $e){
            return ['status'=>"error","message"=>'删除订单时出错：'.$e->getMessage()];
        }
    }

    /**
     * 重新执行域名验证
     * @return array
     */
    public function recheckDomainValidation() {
        try{
            $site = SiteRep::getSiteInfo(_post('siteName'));
            $db = DatabaseUtils::initLocalDatabase();
            // 查询当前状态
            $order = $db->query("select * from certificate where site_id = ?", ($site['id']))->fetch();
            if(empty($order)){
                return  ['status'=>'error','message'=>"不存在对应的证书订单"];
            }
            // 执行远端的API订单验证检查
            return Encryption365Service::certReValidation($order->vendor_id);
        }catch (\Exception $e){
            return ['status'=>"error","message"=>'操作失败：'.$e->getMessage()];
        }
    }

    /**
     * 检查最新的客户端版本
     * @return array
     */
    public function checkUpdateVersion() {
        try{
            $localVersion = Encryption365Service::getClientVersion();
            $rep = Encryption365Service::checkUpdateVersion();
            if(isset($rep['latest_version']) && $rep['latest_version'] > $localVersion){
                return [
                    'status'=>'success',
                    'updateVersion'=>$rep['latest_version'],
                    'updateDescription'=>$rep['update_description'],
                ];
            }else{
//                return ['status' => "error"];
            }
        }catch (\Exception $e){
            return ['status'=>"error","message"=>'操作失败：'.$e->getMessage()];
        }
    }

    /**
     * @return array|string
     */
    public function getOrgTemplateList() {
        $start = _post('start')==""?0:_post('start');
        $draw = _post('draw');
        $length = _post('length')==""?6:(_post('length')>20?20:_post('length'));
        $search = _post('search[value]') != ""?_post('search[value]'):NULL;
        $db = DatabaseUtils::initLocalDatabase();
        try{
            if($search !== NULL){
                $sites = $db->query('SELECT * FROM organization_template where organization_template.organization_name LIKE ? order by organization_template.id desc limit ? offset ? ', "%$search%", $length,$start)->fetchAll();
                $recordsFiltered = ($db->query('select count(id) as total from organization_template where organization_template.organization_name LIKE ?', "%$search%")->fetch())['total'];
            }else{
                $sites = $db->query('SELECT * FROM organization_template order by organization_template.id desc limit ? offset ? ', $length,$start)->fetchAll();
                $recordsFiltered = ($db->query('select count(id) as total from organization_template')->fetch())['total'];
            }
            $recordsTotal = ($db->query('select count(id) as total from organization_template')->fetch())['total'];
        }catch(\Exception $exception){
            return $exception->getMessage();
        }

        $sites = json_decode(json_encode($sites), 1);

        return array(
            'data'=>$sites,
            'draw'=>$draw,
            "recordsTotal"=> $recordsTotal,
            "recordsFiltered"=>$recordsFiltered
        );
    }

    /**
     * 更新组织模板信息
     * @return array
     */
    public function updateOrganizationDetails() {
        try{
            $db = DatabaseUtils::initLocalDatabase();
            $keys = [
                'organization_name',
                'organizationalUnitName',
                'registered_address_line1',
                'registered_no',
                'country',
                'state',
                'city',
                'postal_code',
                'organization_phone',
                'date_of_incorporation',
                'contact_name',
                'contact_title',
                'contact_phone',
                'contact_email'
            ];
            $newOrg = [];
            foreach ($keys as $name){
                $newOrg[$name] = _post($name);
            }

            $db->query('update organization_template set', $newOrg,'where id =?', _post('org_id'));
            LogUtils::writeLog(LogUtils::STATUS_SUCCESS,LogUtils::TITLE_ORG_UPDATE,'组织信息保存/更新成功, 组织:'._post('organization_name'));
            return ['status'=>"success"];
        }    catch (\Exception $e){
            LogUtils::writeLog(LogUtils::STATUS_ERROR,LogUtils::TITLE_ORG_UPDATE,'组织信息保存失败, 组织:'._post('organization_name'));
            return ['status'=>"error","message"=>'保存出错，信息格式可能出现错误'];
        }
    }

    /**
     * @return string
     * @throws \Twig\Error\LoaderError
     * @throws \Twig\Error\RuntimeError
     * @throws \Twig\Error\SyntaxError
     */
    public function createOrganization() {

templates/PHPRequirements.html.twig
<div class="page-desc">
    <div class="enc365-page-title">升级您的PHP环境</div>
    运行Encryption365客户端时可能遇到了一些问题, 请您参考下列提示来解决并重新运行Encryption365客户端。
</div>
{# 服务器基本信息 #}
<div>
    {% for error in errors %}
    <div class="line">
        <span class="to_tvalue" style="height: auto;">
            <p style="color: red; font-weight: 600;font-size: 15px;">{{ error.title }}</p>
            {{ error.desc }}
        </span>
    </div>
    {% endfor %}
    <div style="margin-top: 20px;">
        <a href="https://board.trustocean.com" class="btn btn-sm btn-primary" target="_blank">从社区中查找解决方案</a>
    </div>
</div>
<p style="color: red;">注意: 部分PHP扩展安装后, 可能需请您卸载并重新安装Encryption365插件后才可正常运行。</p>

templates/addFunds.html.twig
<div class="page-desc">
    <div class="enc365-page-title">账户充值</div>
    为您的环智中诚™账户储值，以确保有足够的余额进行自动续费和申请商业SSL证书。
</div>
{# 支付方式信息 #}
<script type="application/javascript" src="/encryption365/static/js/qrcode.js"></script>
<div>
    <div class="line">
        <span class="tname">当前余额</span>
        <span class="to_tvalue">{{ account.credit }} 元</span>
    </div>
    <form id="addFunds">
    <div class="line">
        <span class="tname">支付方式</span>
        <span class="to_tvalue" style="height: auto; padding-left: 100px; margin-bottom: 15px;"><div class="logo-alipay" style="height: 30px;"></div></span>
    </div>
    <div class="line">
        <span class="tname">充值金额</span>
        <span class="to_tvalue">
            <input name="amount" class="bt-input-text" type="text" onkeyup="this.value=/^[0-9]*\.?[0-9]{0,2}$/.test(this.value) ? this.value : this.value.substring(0,this.value.length-1)" maxlength="9" minlength="1" required placeholder="如: 500.00">
        </span>
    </div>
    <div class="line">
        <button class="btn btn-sm btn-success" type="submit" style="margin-left: 100px;">立即充值</button>
    </div>
    </form>
</div>

<div style="margin-top: 15px;">
    <p style="margin-bottom: 10px;">提示信息:</p>
    <ul>
        <li>1.如需对公付款, 请通过左侧帮助菜单联系我们获取对公付款信息和确认流程。</li>
    </ul>
</div>

<script>
    $('form#addFunds').submit(function(e){
        e.preventDefault(); // 禁止常规提交
        encryption365.tryToAddFunds($('form#addFunds'));
    });
</script>

templates/clientInfo.html.twig
<div class="page-desc">
    <div class="enc365-page-title">客户端状态</div>
    此页面展示了您本地客户端的绑定信息和运行状态, 同个 环智中诚™ 账户可以注册多个 Encryption365 客户端。
</div>
{# 服务器基本信息 #}
<div>
    <div class="line">
        <span class="tname">运行状态</span>
        <span class="to_tvalue">{{ client.client_status|upper }}</span>
    </div>
    <div class="line">
        <span class="tname">注册日期</span>
        <span class="to_tvalue">{{ client.registered_at }}</span>
    </div>
    <div class="line">
        <span class="tname">软件版本</span>
        <span class="to_tvalue">{{ client.version }}</span>
    </div>
    <div class="line">
        <span class="tname">绑定账户</span>
        <span class="to_tvalue">{{ client.acc_email }}</span>
    </div>
    <div class="line">
        <span class="tname">客户端IP</span>
        <span class="to_tvalue">{{ client.ip_address }}</span>
    </div>
    <div class="line">
        <span class="tname">客户端ID</span>
        <span class="to_tvalue">{{ client.client_id|upper }}</span>
    </div>
</div>

templates/clientLogs.html.twig
<div class="page-desc">
    <div class="enc365-page-title">客户端操作日志</div>
    此页面列出了自您安装 Encryption365 客户端以来的操作日志和定时任务(CronTab)的运行日志, 便于您审计操作和查看历史。
</div>

<table id="sites" class="table table-hover encryption365-table divtable " style="width:100%">
    <thead>
    <tr>
        <th>编号</th>
        <th>状态</th>
        <th>详情</th>
        <th>操作时间</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td colspan="8" style="text-align: center;">
            <img src="/encryption365/static/img/ajax-loader.gif" style="height: 15px;"> 数据加载中...
        </td>
    </tr>
    </tbody>
</table>


<script type="text/javascript">
    $(document).ready(function() {
        $('#sites').DataTable( {
            "processing": true,
            "serverSide": true,
            "paging": true, //开启分页
            "ajax": {
                url:'/plugin?action=a&s=getClientLogList&name=encryption365',
                type:'POST'
            },
            "ordering":false,
            "columns": [
                {"data":null,
                    render: function(row, index){
                        return row.id;
                    }
                },
                {"data":null,
                    render:function(row, index){
                        if("success"===row.status){
                            return "成功"
                        }else{
                            return "失败"
                        }
                    }
                },
                {"data":null,
                    render:function(row, index){
                        return row.description
                    }
                },
                {"data":null,
                    render:function(row, index){
                        return formatDateToNormal(row.created_at)
                    }
                },
            ],
            "language": {
                'loadingRecords': '&nbsp;',
                'processing': '<div class="spinner"></div>',
                "lengthMenu": "每页显示 _MENU_ 项记录",
                "zeroRecords": "没有找到相应的记录",
                "info": "第 _START_ 至 _END_ 行，共 _TOTAL_ 行",
                "infoEmpty": "第 0 至 0 项结果，共 0 项",
                "infoFiltered": "(从 _MAX_ 项记录中搜索)",
                "infoPostFix": "",
                "search": "搜索日志:",
                "searchPlaceholder": "输入关键词查找...",
                "url": "",
                "thousands": "'",
                "emptyTable": "当前客户端还没有操作日志",
                "infoThousands": ",",
                "paginate": {
                    "first": "首页",
                    "previous": "上页",
                    "next": "下页",
                    "last": "末页"
                }
            },
            "pageLength": 12,
            "lengthMenu": [12, 15, 18, 20],
            "stateSave": false,
            "autoWidth": true,
        } );
    } );

function formatDateToNormal(time) {
    var date = new Date(time);
    var year = date.getFullYear(),
        month = date.getMonth() + 1,//月份是从0开始的
        day = date.getDate(),
        hour = date.getHours(),
        min = date.getMinutes(),
        sec = date.getSeconds();
    var newTime = year + '-' +
        month + '-' +
        day + ' ' +
        hour + ':' +
        min + ':' +
        sec;
    return newTime;
}
</script>

templates/createSSLOrder.html.twig
{% include "common.html.twig" %}
<style>
    .bt-w-main{
        height: 738px !important;
    }
    .layui-layer.layui-layer-page{
        height: 780px !important;
    }
</style>
<div class="page-desc">
    <div class="enc365-page-title">申请 SSL 证书</div>
    立即为您的站点创建安全证书，实现自动化部署和续费 SSL 证书, 选择最佳的证书产品
</div>
{# 服务器基本信息 #}
<div class="row" style="margin: 0px;">
    <div class="col-md-6" style="padding: 0px;width: 52%;padding-right: 5px;">
        <div class="line">
            <div style="margin-bottom: 10px;">选择类型</div>
            <div class="to_tvalue" style="display: block; height: auto;">
                {% for pid,product in products %}
                    <div class="to-cart ssl-product" data-pid="{{ pid }}" style="background-image: url('{{ product.logo }}');{% if product.promote is same as(false) and product.recommended is same as(false)%}padding-bottom: 20px;{% endif %}">
                        <label data-pid="{{ pid }}" data-level="{{ product.level }}" {% if product.default is same as(true) %}data-default-selected{% endif %} data-price-fqdn="{{ product.price.fqdn }}" data-period-text="{{ product.periodText }}" data-price-wildcard="{{ product.price.wildcard }}" data-price-ipv4="{{ product.price.fqdn }}" onclick="encryption365.localCartTotal(this)">
                            <input type="radio" name="pid" data-level="{{ product.level }}" value="{{ pid }}" {% if product.default is same as(true) %}checked{% endif %}>
                            <span>{{ product.title }}</span>
                            <table>
                                <tbody>
                                <tr>
                                    <td><span>适用:</span> {{ product.useage }}</td>
                                    <td><span>级别:</span> {{ product.class }}</td>
                                    <td><span>有效期:</span> {{ product.term }}</td>
                                    <td><span>技术支持:</span> {% if product.support is same as(false) %}无{% else %}有{% endif %}</td>
                                </tr>
                                </tbody>
                            </table>
                        </label>
                        {% if product.promote is same as(true) %}
                            <span class="to-cart-promo">{{ product.promoText }}</span>
                        {% endif %}
                        {% if product.recommended is same as(true) %}
                            <span class="to-cart-recom">推荐</span>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="line" style="padding-top: 0px;">
            <div class="to_tvalue" style="height: auto;">
                <div>网站域名</div>
                {% if site.site_domains is not empty %}
                    <textarea disabled style="padding: 5px 10px;margin: 0px; width: 100%; height: 116px; line-height: 18px; border: 1px solid rgb(221, 221, 221);">{% for domain in site.site_domains %}{{ domain }}
{% endfor %}</textarea>
                {% else %}
                    暂无域名
                {% endif %}
            </div>
        </div>

        <div class="line" id="orgSelection" style="margin-top: 15px;display: none;">
            <span class="to_tvalue" style="height: auto;">
                <div>申请人信息</div>
                <label style="width: 100%;display: block;color: #757575; font-weight: 500;">
                    <select name="org" class="form-control input-sm" style="width: 100%;">
                        <option value="-1">-- 请选择企业/组织信息 --</option>
                        {% for org in orgs %}
                            <option value="{{ org.id }}">{{ org.organization_name }}</option>
                        {% endfor %}
                    </select>
                    <p>请选择作为此证书申请人的组织/企业信息, <a href="#" onclick="encryption365.page('createOrganization',{},'处理中')" style="color: #00a907;">点此创建新的信息模板</a></p>
                </label>
            </span>
        </div>
    </div>
    <div class="col-md-5" style="padding: 0px;width: 48%;padding-left: 10px;">
{#        <div class="line">#}
{#            <span class="tname">网站名称</span>#}
{#            <span class="to_tvalue">{{ site.name }}</span>#}
{#        </div>#}
{#        <div class="line">#}
{#            <span class="tname">网站目录</span>#}
{#            <span class="to_tvalue" style="height: auto; word-break: break-all; padding-left: 100px;"><span class="glyphicon glyphicon-folder-open enc365-icon-folder" onclick="encryption365.openPath('{{ site.path }}')"></span>  {{ site.path }}</span>#}
{#        </div>#}
        <div class="line">
            <span class="to_tvalue to-domain-ans" style="height: auto;font-weight: 500;margin-left: 0px">
                <div>费用详情</div>
                <table>
                    <thead>
                        <tr>
                            <th>类型</th>
                            <th>数量</th>
                            <th>单价</th>
                            <th>小计</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if site.valid_cert_domains_count.fqdn > 0 %}
                            <tr>
                                <td>一般域名</td>
                                <td><span data-fqdn="{{ site.valid_cert_domains_count.fqdn }}">{{ site.valid_cert_domains_count.fqdn }}</span> 条</td>
                                <td><span data-domain-price-fqdn>-</span> 元</td>
                                <td><span data-domain-pricet-fqdn>-</span> 元</td>
                            </tr>
                        {% endif %}
                        {% if site.valid_cert_domains_count.ipv4 > 0 %}
                            <tr>
                                <td>公网IPv4</td>
                                <td><span data-ipv4="{{ site.valid_cert_domains_count.ipv4 }}">{{ site.valid_cert_domains_count.ipv4 }}</span> 个</td>
                                <td><span data-domain-price-ipv4>-</span> 元</td>
                                <td><span data-domain-pricet-ipv4>-</span> 元</td>
                            </tr>
                        {% endif %}
                        {% if site.valid_cert_domains_count.wildcard > 0 %}
                            <tr>
                                <td>通配符组</td>
                                <td><span data-wildcard="{{ site.valid_cert_domains_count.wildcard }}">{{ site.valid_cert_domains_count.wildcard }}</span> 组</td>
                                <td><span data-domain-price-wildcard>-</span> 元</td>
                                <td><span data-domain-pricet-wildcard>-</span> 元</td>
                            </tr>
                        {% endif %}
                        <tr>
                            <td colspan="3" style="text-align: right">合计: </td>
                            <td style="color: #888888;"><span data-toCartTotal style="color: #ff6232;">--.--</span> 元/<span data-toCartPeriod></span></td>
                        </tr>
                    </tbody>
                </table>
                <p style="color: #828282;">说明: 根据域名类型的不同，多种域名费用组成证书总费用</p>
            </span>
        </div>
        <div class="line">
            <span class="to_tvalue" style="height: auto;">
                <div>自动续费</div>
                <label style="width: 100%;display: block;color: #757575; font-weight: 500;">
                    <input name="autorenewal" type="checkbox" checked="checked">
                    <span>开启自动续费</span>
                    <p>开启后将在到期前尝试申请、更新证书并收取费用。</p>
                </label>
            </span>
        </div>
        <div class="line">
            <span class="tname" style="width: 70px;">费用总计</span>
            <span class="to_tvalue">
                <div class="cart-total"><span data-toCartTotal>--.--</span>元/<span data-toCartPeriod></span></div>
            </span>
        </div>
        <div class="line">
            <span class="to_tvalue">
                <button onclick="javascript:encryption365.createNewFullSSL('{{ site.name }}',$('input[name=pid]:checked').val(), $('input[name=pid]:checked').data('level'), $('select[name=org]').val(),$('input[name=autorenewal]').is(':checked'));" class="btn btn-success btn-sm" title="立即申请"> 立即部署安全证书</button>
                <button onclick="javascript:encryption365.page('siteSetting',{siteName:'{{ site.name }}'});" class="btn btn-default btn-sm btn-nobg" title="返回站点详情" style="color: #8c8b8b !important;"> 放弃申请</button>
            </span>
        </div>
    </div>
</div>
<script>
    // 初始化购物车价格
    encryption365.localCartTotal($('label[data-default-selected]'));
    // 更好的购物车产品点击捕获
    $('div.to-cart.ssl-product').click(function(){
        $(this).children()[0].click();
    })
</script>

templates/getSupport.html.twig
<div class="page-desc">
    <div class="enc365-page-title">获取帮助</div>
    当您在使用过程中遇到问题时，您可以通过下面列出的联系方式联系我们获取帮助。
</div>
{# 服务器基本信息 #}
<div>

    <div class="line">
        <span class="tname">工作时间</span>
        <span class="to_tvalue">每 周一 至 周五, 9:00 - 18:00</span>
    </div>
    <div class="line">
        <span class="tname">客服 QQ</span>
        <span class="to_tvalue"><a href="https://wpa1.qq.com/PFVEyXqF?_type=wpa&qidian=true" target="_blank">800183788</a></span>
    </div>
    <div class="line">
        <span class="tname">热线电话</span>
        <span class="to_tvalue">+86 4009030029</span>
    </div>
    <div class="line">
        <span class="tname">备用电话</span>
        <span class="to_tvalue">+86 02988188289</span>
    </div>
    <div class="line">
        <span class="tname">官方网址</span>
        <span class="to_tvalue">https://www.trustocean.com</span>
    </div>
    <div class="line">
        <span class="tname">BUG反馈</span>
        <span class="to_tvalue"><a href="https://github.com/londry/Encryption365_Baota/issues" target="_blank">>> 前往GitHub问题反馈页面</a></span>
    </div>
    <div class="line">
        <span class="tname">证书问答</span>
        <span class="to_tvalue"><a href="https://www.secoper.com/question" target="_blank">>> 访问SSL证书产品交流和技术问答中心</a></span>
    </div>
</div>

templates/ioncubeRequired.html.twig
<div class="page-desc">
    <div class="enc365-page-title">需要安装PHP扩展</div>
    运行Encryption365客户端时可能遇到了一些问题, 请您参考下列提示来解决并重新运行Encryption365客户端。
</div>
{# 服务器基本信息 #}
<div>
    <div class="line">
        <span class="to_tvalue" style="height: auto;">
            <p style="color: red; font-weight: 600;font-size: 15px;">PHP 缺少 Ioncube 扩展</p>
            监测到您的PHP环境不满足运行要求，请您前往 PHP {{ php_verison }} 的配置页面来安装 Ioncube Loader 加密扩展。安装完成后重新尝试运行客户端。
            <p style="color: red;">注意: 完成Ioncube安装后, 可能需请您卸载并重新安装Encryption365插件后才可正常运行。</p>
        </span>
    </div>
</div>

templates/onlineSupport.html.twig
<div class="page-desc">
    <div class="enc365-page-title">在线支持</div>
    通过在线聊天软件联系我们的工作人员，进入交流群提问以获取及时的答复，社区解答更加快捷。
</div>
{# 服务器基本信息 #}
<div>
    <div>
        <img style="height: 200px; padding: 10px; border: 1px solid #ddd;" src="https://www.qiaokr.com/wp-content/uploads/2021/04/ebd8e343-9c2e-4fb2-897b-204645312d01.jpg">
    </div>
</div>

templates/pageException.html.twig
<div class="page-desc">
    <div class="enc365-page-title">有点小问题</div>
    运行Encryption365客户端时可能遇到了一些问题, 请您参考下列提示来解决并重新运行Encryption365客户端。
</div>
{# 服务器基本信息 #}
<div>
    <div class="line">
        <span class="to_tvalue" style="height: auto;">
            <p style="color: red; font-weight: 600;font-size: 15px;">{{ title }}</p>
            {{ message }}
            <p><button onclick='encryption365.page("clientInfo")' class="btn btn-sm btn-success">查看账户信息</button></p>
        </span>
    </div>
</div>